# Generated by Django 5.0.4 on 2024-06-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("disasters", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "City", "verbose_name_plural": "Cities"},
        ),
        migrations.AlterModelOptions(
            name="disastertype",
            options={
                "verbose_name": "Disaster Type",
                "verbose_name_plural": "Disaster Types",
            },
        ),
    ]
